databases:
  - name: the_toy_app_nellaaa
    databaseName: the_toy_app_nellaaa
    user: the_toy_app_nellaaa_user

services:
  - type: web
    name: the_toy_app_nellaaa
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: the_toy_app_nellaaa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false